language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install --upgrade cython falcon"
  - "pip install --force-reinstall --upgrade cython"
  - "pip install --force-reinstall --upgrade falcon"
  - "pip install --upgrade gevent gunicorn"
  - "pip install -r requirements-dev.txt"
  - "python setup.py install"
# command to run tests
script: " python tests/resource_test.py"